baseURL = "https://docs.o3de.org"
title = "Open 3D Engine"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "O3DE Authors | Documentation Distributed under CC-BY 4.0"

enableGitInfo = true
enableRobotsTXT = true 

[markup.highlight]
style = "paraiso-dark"

[markup.goldmark.renderer]
unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]

[params]
font_awesome_version = "5.12.0"
description = "Open 3D Engine (O3DE) is an Apache 2.0-licensed multi-platform 3D engine that enables developers and content creators to build AAA games, cinema-quality 3D worlds, and high-fidelity simulations <b>without any fees or commercial obligations</b>.<br><br><b>Try the Developer Preview today!</b>"
favicon = "favicon.png"
repositoryUrl = "https://github.com/o3de/o3de.org"
contentDir = "/content/"
sourceRepo = "https://github.com/o3de/o3de"

[params.logos]
navbar = "O3DE-Logo-REV-Mono.svg"

[[params.social]]
name = "Twitter"
url = "#"
icon = "fab fa-twitter"

[[params.social]]
name = "GitHub"
url = "https://github.com/o3de"
icon = "fab fa-github"

[[params.social]]
name = "Discord"
url = "#"
icon = "fab fa-discord"

[[params.social]]
name = "Slack"
url = "#"
icon = "fab fa-slack"

[[params.fonts]]
name = "Open Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[params.fonts]]
name = "Open Sans"
sizes = [100, 200, 300, 400, 500, 600, 700]
type = "heading_font"

[[menu.main]]
name = "DOWNLOAD"
url = "/download"
weight = 1

# [[menu.main]]
# name = "News"
# url ="#"
# weight = 2

[[menu.main]]
name = "GET STARTED"
url = "/docs/welcome-guide"
weight = 3

[[menu.main]]
name = "COMMUNITY"
url = "/community"
weight = 4
identifier = "community"

# [[menu.main]]
# name = "Community subitem placeholder"
# url = "#"
# weight = 5 
# parent = "community"

[[menu.main]]
name = "LEARN"
url = "/docs"
weight = 6
identifier = "docs"

[[menu.main]]
name = "CONTRIBUTE"
url = "/docs/contributing"
weight = 7
